### ISSUE TITLE
ResponseFormat type

### ISSUE THREAD

**Issue by gusmally** [lofcz/OpenAiNg#6]
I'm surprised that ChatRequest.ResponseFormat is type ChatRequestResponseFormats instead of ChatRequestResponseFormatTypes. Can you explain what I'm missing or a cleaner way to do it?

e.g.:

wanting to do:
```
    ResponseFormat = ChatRequestResponseFormatTypes.Text,
```

instead of:
```
var textType = new ChatRequestResponseFormats();
textType.Type = ChatRequestResponseFormatTypes.Text;
...
    ResponseFormat = textType,
```

(actually I am swapping between text and json but that's not relevant for this example)

**Comment by lofcz** [comment]
You are correct, this will be fixed.

**Comment by lofcz** [comment]
This is now fixed in f4108526b6b151e80d1650f7c856be9e9db6f821 the usage should be:

```cs
ChatResult result = await Program.Connect().Chat.CreateChatCompletionAsync(new ChatRequest
{
    Model = Models.Model.GPT4_Turbo_Preview,
    ResponseFormat = ChatRequestResponseFormats.Json,
    Messages = [
        new ChatMessage(ChatMessageRole.System, "Solve the math problem given by user, respond in JSON format."),
        new ChatMessage(ChatMessageRole.User, "2+2=?")
    ]
});
```

**Comment by gusmally** [comment]
thank you for the quick response and fix! :raised_hands:

**Comment by lofcz** [comment]
The fix is available in https://www.nuget.org/packages/OpenAiNg/3.0.0-beta2
