### ISSUE TITLE
Have you considered using HTTP/2 for the EndpointClient?

### ISSUE THREAD

**Issue by mikethea1** [lofcz/OpenAiNg#7]
I see that the endpoint client sets MaxConnectionsPerServer and PooledConnectionLifetime to help control connection management, but my understanding is that leveraging HTTP/2 (or higher) can also help with this problem by multiplexing connections:

```
HttpClient EndpointClient = new(new SocketsHttpHandler
{
	MaxConnectionsPerServer = 10000,
	PooledConnectionLifetime = TimeSpan.FromMinutes(2)
})
{
	Timeout = TimeSpan.FromSeconds(600),
	DefaultRequestVersion = new(2, 0) // default to higher version
};
```

I'm curious whether you've found a reason to be using 1.1 instead?

**Comment by lofcz** [comment]
Originally this was due to the old servers we used but that no longer applies, thanks for suggestion, implemented in 6ede9b28e6f67bd311a82fd692a53217b74697d3
