### ISSUE TITLE
Should ChatMessage.Name be nullable?

### ISSUE THREAD

**Issue by mikethea1** [lofcz/OpenAiNg#9]
My understanding is that this property is optional; the doc comment even says so. Shouldn't this be marked as nullable?

**Comment by lofcz** [comment]
Yes, it should. I'm working on finishing the Assistants support, after that I will dust off the older APIs and make sure all nullability annotations match.

**Comment by lofcz** [comment]
This is now fixed in 80d995b7d935e82eae29a5dbc43493cbcdb87831
